//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTUDQL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapDo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CapDo()
        {
            this.User = new HashSet<User>();
            this.UserThanhToan = new HashSet<UserThanhToan>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> Phi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserThanhToan> UserThanhToan { get; set; }
    }
}
