//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTUDQL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Playlist
    {
        public int UserProfileID { get; set; }
        public int ProfileID { get; set; }
        public int PhimID { get; set; }
        public Nullable<System.TimeSpan> ThoiGianXem { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
